export const ActionTypes = {
    POST_CREATE: "POST_CREATE",
    POST_CREATE_SUCCESS: "POST_CREATE_SUCCESS",
    POST_CREATE_COMPLETED: "POST_CREATE_COMPLETED",
    POST_CREATE_ERROR: "POST_CREATE_ERROR",
    FETCH_POSTS: "FETCH_POSTS",

}