export const ActionTypes = {
    POST_CREATE: "POST_CREATE",
    POST_CREATE_CANCEL: "POST_CREATE_CANCEL",
    POST_CREATE_SUCCESS: "POST_CREATE_SUCCESS",
    POST_CREATE_COMPLETED: "POST_CREATE_COMPLETED",
    POST_CREATE_ERROR: "POST_CREATE_ERROR",

    FETCH_POSTS: "FETCH_POSTS",

}

export const Statuses = {
    // adding posts statuses
    POST_STATUS_IDLE: "POST_STATUS_IDLE",
    POST_STATUS_PENDING: "POST_STATUS_PENDING",
    POST_STATUS_COMPLETED: "POST_STATUS_COMPLETED",
    POST_STATUS_ERROR: "POST_STATUS_ERROR",
    //fetching posts statuses
    FETCHING_STATUS_IDLE: "FETCHING_STATUS_IDLE",
    FETCHING_STATUS_PENDING: "FETCHING_STATUS_PENDING",
    FETCHING_STATUS_COMPLETED: "FETCHING_STATUS_COMPLETED",
    FETCHING_STATUS_ERROR: "FETCHING_STATUS_ERROR",


}